#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'dayOfProgrammer' function below.
#
# The function is expected to return a STRING.
# The function accepts INTEGER year as parameter.
#
def day(n):
    s=0
    for i in range(0,n):
        if(i%2==0):
            s+=31
        else:
            s+=30
    return s
def dayOfProgrammer(year):
    # Write your code here
    j=k=0
    if(year<1918):
        if(year%4!=0):
            j=1
    elif(year>1918):
        if(year%400!=0 and (year%4!=0 or year%100==0)):
            j=1
    else:
        k=14
    k+=9/100+(256-(day(8)-j))
    return str(k)+"."+str(year)
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    year = int(input().strip())

    result = dayOfProgrammer(year)

    fptr.write(result + '\n')

    fptr.close()
