#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'sockMerchant' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY ar
#
def sockMerchant(n, ar):
    # Write your code here
    dict={}
    c=0
    for i in ar:
        if(i in dict):
            dict[i]+=1
        else:
            dict[i]=1
    a=dict.values()
    for i in a:
        if(i%2==0):
            c+=i/2
        else:
            c+=i//2
    return int(c)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
