#!/bin/python3

import math
import os
import random
import re
import sys
def greater(a,b):
    if(a>b):
        return a-b
    else:
        return b-a
# Complete the catAndMouse function below.
def catAndMouse(x, y, z):
    x=greater(x,z)
    y=greater(y,z)
    if(x<y):
        return "Cat A"
    elif(x>y):
        return "Cat B"
    else:
        return "Mouse C"
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        xyz = input().split()

        x = int(xyz[0])

        y = int(xyz[1])

        z = int(xyz[2])

        result = catAndMouse(x, y, z)

        fptr.write(result + '\n')

    fptr.close()
